version: 2.1


orbs:
  hello-build: circleci/hello-build@0.0.9

executors:
  python_docker:
    docker:
      - image: circleci/python:3.7-node-browsers-legacy

jobs:

  say-hello:
    executor: python_docker
    parameters:
      to:
        default: ${CIRCLE_USERNAME}
        type: string
    steps:
      - hello-triggerer:
          to: <<parameters.to>>

  build:
    executor: python_docker
    steps:
      - checkout:
          path: ~/project
      - run:
          command: |
            ls -al
            sudo chown -R circleci:circleci .
            chmod -R +rwx ./ci
            ./ci/setup.sh
          name: Setup
      - run:
          command: ./ci/run_tests.sh
          name: Run tests
      - store_artifacts:
          path: reports
      - run:
          command: tar -cvf package.tar .
          name: Create Package
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./*.tar

  deploy:
    executor: node
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Content to deploy
          command: ls
      - deploy:
          name: Deploy artifacts
          command: echo 'deploying....'


workflows:
  build-test-deploy:
    jobs:
      - say-hello:
      - build:
          requires:
            - say-hello
      - deploy:
          requires:
            - build