version: 2.1


executors:
  node:
    docker:
      - image: circleci/python:3.7-node-browsers-legacy

jobs:
  build:
    executor: node
    steps:
      - checkout:
          path: ~/project
      - run:
          command: |
            ls -al
            sudo chown -R circleci:circleci .
            chmod -R +rwx ./ci
            ./ci/setup.sh
          name:
      - run:
          command: ./ci/run_tests.sh
          name: Run tests
workflows:
  build-test-deploy:
    jobs:
      - build